pipeline {
    agent { label 'cicd' }

    stages {
        stage("build") {
            steps {
                echo "building the application..."
                echo "Hi Davshe"
            }
        }

        stage("test") {
            steps {
                echo "testing the application..."
            }
        }

        stage("deploy") {
            steps {
                echo "deploying the application..."
            }
        }

    }
}
